version: "3.7"

services:

  # app:
  #   build:
  #     dockerfile: docker/app/Dockerfile
  #     context: .
  #   volumes:
  #     - ./src:/usr/src/app:delegated
  #   ports:
  #     - "6794:6794"
  #   environment:
  #     PORT: "6794"
  #   entrypoint:
  #     - yarn
  #     - serve

  cli:
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    volumes:
      - ./src:/usr/src/app:delegated
    ports:
      - "6794:6794"
    environment:
      PORT: "6794"
    entrypoint:
      - sh
      - -c
      - sleep 1000000

  mock_api:
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    volumes:
      - ./src:/usr/src/app:delegated
    # ports:
    #   - "4976:4976"
    expose:
        - "3000"
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
    entrypoint:
      - node
      - ./mock_api/index.js
  mock_api_proxy:
    build:
      dockerfile: ./Dockerfile
      context: docker/mock_api/nginx/
    # volumes:
      # - ./src:/usr/src/app:delegated
    ports:
      - "4976:80"
    environment:
      # FQDN: "localhost"
      HTTP_PORT: "80"
      TARGET_SERVICE: "mock_api:3000"
      CORS_ALLOW_DOMAINS_REGEX: '"http://localhost:6794"'

  lesschrome:
    build:
      dockerfile: ./Dockerfile
      context: docker/headless-chrome/
    volumes:
      - ./src/tests/browser/media:/media:delegated
    shm_size: '1gb'
    # cap_add:
    #   - SYS_ADMIN
    environment:
      PORT: "9222"
    expose:
      - "9222"
    ports:
      - '9222:9222'
