version: "3.7"

services:


  # app:
  #   build:
  #     dockerfile: docker/app/Dockerfile
  #     context: .
  #   volumes:
  #     - ./src:/usr/src/app:delegated
  #   ports:
  #     - "6794:6794"
  #   environment:
  #     PORT: "6794"
  #   entrypoint:
  #     - yarn
  #     - serve


  cli:
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    volumes:
      - ./src:/usr/src/app:delegated
    ports:
      - "6794:6794"
    expose:
      - "6794"
    environment:
      PORT: "6794"
      # _mock_
      # MOCK_ENABLED: "false"
      # MOCK_BACKEND_ENDPOINT: "http://mock_api:4976"
      VUE_APP_BACKEND_ENDPOINT: "http://localhost:4976"
      # _normal_
      # VUE_APP_BACKEND_ENDPOINT: "localhost:6793"
    entrypoint:
      - sh
      - -c
      - sleep 1000000


  mock_api:
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    volumes:
      - ./src:/usr/src/app:delegated
    # ports:
    #   - "4976:4976"
    expose:
        - "3000"
    ports:
      - "3000:3000"
    # environment:
    #   PORT: "3000"
    entrypoint:
      - node
      - ./mock_api/index.js
  mock_api_proxy:
    build:
      dockerfile: ./Dockerfile
      context: docker/mock_api/nginx/
    # volumes:
      # - ./src:/usr/src/app:delegated
    ports:
      - "4976:80"
    environment:
      # FQDN: "localhost"
      HTTP_PORT: "80"
      TARGET_SERVICE: "mock_api:3000"
      #cli:6794
      CORS_ALLOW_DOMAINS_REGEX: '"http://localhost:6794"'


  selenium:
    image: selenium/hub:3.14.0
    environment:
      - GRID_MAX_SESSION=2
      - GRID_BROWSER_TIMEOUT=100000
      - GRID_TIMEOUT=90000
      - GRID_NEW_SESSION_WAIT_TIMEOUT=300000
    # ports:
    #   - "4444:4444"
    expose:
      - "4444"
  chrome:
    image: selenium/node-chrome:3.14.0
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium
      - HUB_PORT_4444_TCP_PORT=4444
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium

