version: "3.7"

services:

  # app:
  #   build:
  #     dockerfile: docker/app/Dockerfile
  #     context: .
  #   volumes:
  #     - ./src:/usr/src/app:delegated
  #   ports:
  #     - "6794:6794"
  #   environment:
  #     PORT: "6794"
  #   entrypoint:
  #     - yarn
  #     - serve

  cli:
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    volumes:
      - ./src:/usr/src/app:delegated
    ports:
      - "6794:6794"
    environment:
      PORT: "6794"
    entrypoint:
      - sh
      - -c
      - sleep 1000000
